import express from "express";
import user from "./user.routes";
import auth from "./auth.routes";
import permissions from "./permissions.routes";
import role from "./roles.routes";
import groups from "./groups.routes";
import resource from "./upload.routes";
import category from "./category.routes";
import product from "./product.routes";
import audit from "./audit.routes";
import order from "./order.routes";
import catalog from "./catalog.routes";
import review from "./review.routes";
import cart from "./cart.routes";
import analytics from "./analytics.routes";
import notification from "./notification.routes";
import search from "./search.routes";
import ad from "./ad.routes";
import shopReview from "./shopReview.routes";
import faq from "./faq.routes";
import conversation from "./conversation.routes";
import dispute from "./dispute.routes";
import question from "./question.routes";
const router = express.Router();

router.get("/healthcheck", (_, res) => res.sendStatus(200));
router.use("/api/user/", user);
router.use("/api/auth/", auth);
router.use("/api/permissions", permissions);
router.use("/api/group/", groups);
router.use("/api/role/", role);
router.use("/api/resources/", resource);
router.use("/api/category/", category);
router.use("/api/product/", product);
router.use("/api/audit/", audit);
router.use("/api/order/", order);
router.use("/api/catalog/", catalog);
router.use("/api/review/", review);
router.use("/api/cart/", cart);
router.use("/api/analytics/", analytics);
router.use("/api/notification/", notification);
router.use("/api/search/", search);
router.use("/api/ads/", ad);
router.use("/api/shop-reviews/", shopReview);
router.use("/api/faqs/", faq);
router.use("/api/conversations/", conversation);
router.use("/api/disputes/", dispute);
router.use("/api/questions/", question);
export default router;
